POST http://localhost:5259/breakfast
Content-Type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Vegan everything! Join us for a",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatemal",
        "Avocado Toast",
        "Omelette",
        "Salada"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
GET http://localhost:5259/Breakfast/506e3cb8-311c-49c8-946d-52f27982aa0a