POST http://localhost:5259/breakfast
Content-Type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Vegan everything! Join us for a",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatemal",
        "Avocado Toast",
        "Omelette",
        "Salada"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
GET http://localhost:5259/Breakfast/48922c01-8f61-40ef-8aa3-870e5a1309d5