@id=0000000000000000-0000-0000-0000-0000000000

PUT  http://localhost:5259/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Vegan everything! Join us for a",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatemal",
        "Avocado Toast",
        "Omelette",
        "Salada"
    ],
    "Sweet": [
        "Cookie"
    ]
}